Task1
HasanMusaraf/freshteam pull request #3
Opened 2022-10-27 14:10 UTC by HasanMusaraf

I have complete Task1's
 b. Add plugin "ember-bootstrap": "2.6.1"
 c. Add plugin "ember-cli-sass": "10.0.0" to use scss.
 d. Add Common Main Left Nav, Header and footer. These are common for all routes.
 e. Add Icon and Image as shown in the design - For icons, use "ember-svg-jar": "2.3.3" plugin

2022-10-27 17:04 UTC, HasanMusaraf commented
I have complete Task1's
b. Add plugin "ember-bootstrap": "2.6.1"
c. Add plugin "ember-cli-sass": "10.0.0" to use scss.
d. Add Common Main Left Nav, Header and footer. These are common for all routes.
e. Add Icon and Image as shown in the design - For icons, use "ember-svg-jar": "2.3.3" plugin

2022-11-08 11:35 UTC, Shalini-Sivakumar requested changes

2022-11-08 11:35 UTC, Shalini-Sivakumar commented on app/styles/app.scss
> +    margin: 0;
Why do we need these styles for all the elements ..?

2022-11-08 11:35 UTC, Shalini-Sivakumar commented on app/styles/sub-styles/nav.scss
> +  display: flex;
No need to use flex here. Since inside this block, you have only one item to display. Please check and remove this.

2022-11-08 11:35 UTC, Shalini-Sivakumar commented on app/templates/application.hbs
> +    <div class="top-nav-tabs">
Instead of having two block elements here (header and div), can you add only one and change the styles? Because here you can add all the styles in one block. That's enough.

2022-11-08 11:35 UTC, Shalini-Sivakumar commented on app/styles/sub-styles/nav.scss
> +  left: 90px;
why is position absolute required here? You added flex and position: absolute . Please check and remove it.

2022-11-08 11:54 UTC, HasanMusaraf commented on app/styles/app.scss
> +    margin: 0;
I have changed

2022-11-08 11:57 UTC, HasanMusaraf commented on app/styles/sub-styles/nav.scss
> +  display: flex;
I have fixed

2022-11-08 12:12 UTC, HasanMusaraf commented on app/templates/application.hbs
> +    <div class="top-nav-tabs">
I have used this for some purpose

2022-11-08 12:46 UTC, HasanMusaraf commented on app/styles/sub-styles/nav.scss
> +  left: 90px;
I have removed display flex from that class.

2022-11-10 13:18 UTC, Shalini-Sivakumar approved these changes

2022-11-10 13:20 UTC, merged